services:
  # ===== Production =====
  web-prod:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: portfolio-web-prod
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook-prod:
    build:
      context: .
      dockerfile: apps/storybook/Dockerfile
    container_name: portfolio-storybook-prod
    ports:
      - '4006:80'
    restart: unless-stopped

  # ===== Staging =====
  web-stg:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: portfolio-web-stg
    ports:
      - '4010:4000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook-stg:
    build:
      context: .
      dockerfile: apps/storybook/Dockerfile
    container_name: portfolio-storybook-stg
    ports:
      - '4016:80'
    restart: unless-stopped
