services:
  web-prod:
    image: ghcr.io/yk-graph/portfolio-web:latest
    container_name: portfolio-web-prod
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook-prod:
    image: ghcr.io/yk-graph/portfolio-storybook:latest
    container_name: portfolio-storybook-prod
    ports:
      - '4006:80'
    restart: unless-stopped
