services:
  web-stg:
    image: ghcr.io/yk-graph/portfolio-web:staging
    container_name: portfolio-web-stg
    ports:
      - '4010:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook-stg:
    image: ghcr.io/yk-graph/portfolio-storybook:staging
    container_name: portfolio-storybook-stg
    ports:
      - '4016:80'
    restart: unless-stopped
