services:
  web-stg:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NOTION_TOKEN: ${NOTION_TOKEN}
        NOTION_DATA_SOURCE_ID: ${NOTION_DATA_SOURCE_ID}
    container_name: portfolio-web-stg
    ports:
      - '4010:4000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  storybook-stg:
    build:
      context: .
      dockerfile: apps/storybook/Dockerfile
    container_name: portfolio-storybook-stg
    ports:
      - '4016:80'
    restart: unless-stopped
