services:
  web-dev:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    container_name: portfolio-web-dev
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - CI=true
    volumes:
      - .:/app
      - web_root_node_modules:/app/node_modules
      - web_app_node_modules:/app/apps/web/node_modules

  storybook-dev:
    build:
      context: .
      dockerfile: apps/storybook/Dockerfile.dev
    container_name: portfolio-storybook-dev
    ports:
      - '4006:4006'
    environment:
      - CI=true
    volumes:
      - .:/app
      - storybook_root_node_modules:/app/node_modules
      - storybook_app_node_modules:/app/apps/storybook/node_modules

volumes:
  web_root_node_modules:
  web_app_node_modules:
  storybook_root_node_modules:
  storybook_app_node_modules:
