FROM node:24-alpine AS base
RUN npm install -g pnpm@11.9.0
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY apps/web/package.json ./apps/web/
COPY apps/storybook/package.json ./apps/storybook/
COPY packages/ui/package.json ./packages/ui/
COPY packages/tailwind-config/package.json ./packages/tailwind-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/
RUN pnpm install --frozen-lockfile

EXPOSE 4006
CMD ["pnpm", "--filter", "storybook", "storybook"]